subplot(3,4,1);
imshow(0);
title('gray scale = 0','fontname','Times New Roman','Color','k','FontSize',12);
hold on;
subplot(3,4,2);
imshow(0.1);
title('gray scale = 0.1','fontname','Times New Roman','Color','k','FontSize',12);
hold on;
subplot(3,4,3);
imshow(0.2);
title('gray scale = 0.2','fontname','Times New Roman','Color','k','FontSize',12);
hold on;
subplot(3,4,4);
imshow(0.3);
title('gray scale = 0.3','fontname','Times New Roman','Color','k','FontSize',12);
hold on;
subplot(3,4,5);
imshow(0.4);
title('gray scale = 0.4','fontname','Times New Roman','Color','k','FontSize',12);
hold on;
subplot(3,4,6);
imshow(0.5);
title('gray scale = 0.5','fontname','Times New Roman','Color','k','FontSize',12);
hold on;
subplot(3,4,7);
imshow(0.6);
title('gray scale = 0.6','fontname','Times New Roman','Color','k','FontSize',12);
hold on;
subplot(3,4,8);
imshow(0.7);
title('gray scale = 0.7','fontname','Times New Roman','Color','k','FontSize',12);
hold on;
subplot(3,4,9);
imshow(0.8);
title('gray scale = 0.8','fontname','Times New Roman','Color','k','FontSize',12);
hold on;
subplot(3,4,10);
imshow(0.9);
title('gray scale = 0.9','fontname','Times New Roman','Color','k','FontSize',12);
hold on;
subplot(3,4,11);
imshow(1);
title('gray scale = 1','fontname','Times New Roman','Color','k','FontSize',12);
hold on;